### ISSUE TITLE
Trace the cause of runtime error whenever an API call is made

### ISSUE THREAD

**Issue by nirogappnith** [nirogappnith/nirog#10]
Currently, whenever an API call is made, we are greeted with a 'Uncaught runtime error' with status code 500
![image](https://github.com/nirogappnith/nirog/assets/163342900/bec66826-b926-4379-8f97-e0c25ca1300d)

Trace the cause of the error and add it in a comment. 
Further, try to fix it if possible.

**Comment by Amrani-Farouk-Hossam-Eddine** [comment]
Hi, i want to try to fix it if possible

**Comment by Sourabh-awasthy** [comment]
are you working on it ?

**Comment by Amrani-Farouk-Hossam-Eddine** [comment]
yes i just started working on it

**Comment by Amrani-Farouk-Hossam-Eddine** [comment]
i solved the problem and it is a tiny issue that was makeing all the problems

**Comment by mehulambastha** [comment]
This issue has been fixed by @Amrani-Farouk-Hossam-Eddine
